/**
 * 

 * @author Pedro Mariano
 * @version 1.0 2013/01/20
 */
:- module givetake.strategy.encodecode.

:- interface.

/**
 * encodecodeHist(Strategy, GodelNumber, CodeHistoryActions, CodeFirstActions).
 */

:- pred encodecodeHist(givetake.strategy.strategy, int, int, int).
:- mode encodecodeHist(in(hist), out, out, out) is det.
:- mode encodecodeHist(out(hist), in, in, in) is semidet.
:- mode encodecodeHist(out(hist), in, out, out) is semidet.
:- mode encodecodeHist(out(hist), out, in, in) is semidet.
:- mode encodecodeHist(out(hist), out, in, out) is nondet.

/**
 * encodecodeHistDet(Strategy, GodelNumber, CodeHistoryActions, CodeFirstActions).
 */

:- pred encodecodeHist_det(givetake.strategy.strategy, int, int, int).
:- mode encodecodeHist_det(out(hist), in, in, in) is det.
:- mode encodecodeHist_det(out(hist), in, out, out) is det.
:- mode encodecodeHist_det(out(hist), out, in, in) is det.
:- mode encodecodeHist_det(out(hist), out, in, out) is multi.

:- implementation.

:- import_module bool, exception.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Definition of exported types

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Definition of private types

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Implementation of exported predicates and functions

:- pragma promise_pure(encodecodeHist_det/4).

encodecodeHist_det(Result::out(hist), GodelNumber::in, CodeHistoryActions::in, CodeFirstActions::in) :-
	(if
		encodecodeHist(R, GodelNumber, CodeHistoryActions, CodeFirstActions)
	then
		Result = R
	else
		throw("encodecodeHist_det/4: invalid integer parameters passed")
	).

encodecodeHist_det(Result::out(hist), GodelNumber::in, CodeHistoryActions::out, CodeFirstActions::out) :-
	(if
		encodecodeHist(R, GodelNumber, CHA, CFA)
	then
		Result = R,
		CodeHistoryActions = CHA,
		CodeFirstActions = CFA
	else
		throw("encodecodeHist_det/4: invalid integer parameters passed")
	).

encodecodeHist_det(Result::out(hist), GodelNumber::out, CodeHistoryActions::in, CodeFirstActions::in) :-
	(if
		encodecodeHist(R, GN, CodeHistoryActions, CodeFirstActions)
	then
		Result = R,
		GodelNumber = GN
	else
		throw("encodecodeHist_det/4: invalid integer parameters passed")
	).

encodecodeHist_det(Result::out(hist), GodelNumber::out, CodeHistoryActions::in, CodeFirstActions::out) :-
	(if
		encodecodeHist(R, GN, CodeHistoryActions, CFA)
	then
		Result = R,
		GodelNumber = GN,
		CodeFirstActions = CFA
	else
		throw("encodecodeHist_det/4: invalid integer parameters passed")
	).

encodecodeHist(history(no, no, no, no, no, no, no, no, no, no), 0, 0, 0).
encodecodeHist(history(yes, no, no, no, no, no, no, no, no, no), 1, 1, 0).
encodecodeHist(history(no, yes, no, no, no, no, no, no, no, no), 2, 2, 0).
encodecodeHist(history(yes, yes, no, no, no, no, no, no, no, no), 3, 3, 0).
encodecodeHist(history(no, no, yes, no, no, no, no, no, no, no), 4, 4, 0).
encodecodeHist(history(yes, no, yes, no, no, no, no, no, no, no), 5, 5, 0).
encodecodeHist(history(no, yes, yes, no, no, no, no, no, no, no), 6, 6, 0).
encodecodeHist(history(yes, yes, yes, no, no, no, no, no, no, no), 7, 7, 0).
encodecodeHist(history(no, no, no, yes, no, no, no, no, no, no), 8, 8, 0).
encodecodeHist(history(yes, no, no, yes, no, no, no, no, no, no), 9, 9, 0).
encodecodeHist(history(no, yes, no, yes, no, no, no, no, no, no), 10, 10, 0).
encodecodeHist(history(yes, yes, no, yes, no, no, no, no, no, no), 11, 11, 0).
encodecodeHist(history(no, no, yes, yes, no, no, no, no, no, no), 12, 12, 0).
encodecodeHist(history(yes, no, yes, yes, no, no, no, no, no, no), 13, 13, 0).
encodecodeHist(history(no, yes, yes, yes, no, no, no, no, no, no), 14, 14, 0).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, no, no, no), 15, 15, 0).
encodecodeHist(history(no, no, no, no, yes, no, no, no, no, no), 16, 16, 0).
encodecodeHist(history(yes, no, no, no, yes, no, no, no, no, no), 17, 17, 0).
encodecodeHist(history(no, yes, no, no, yes, no, no, no, no, no), 18, 18, 0).
encodecodeHist(history(yes, yes, no, no, yes, no, no, no, no, no), 19, 19, 0).
encodecodeHist(history(no, no, yes, no, yes, no, no, no, no, no), 20, 20, 0).
encodecodeHist(history(yes, no, yes, no, yes, no, no, no, no, no), 21, 21, 0).
encodecodeHist(history(no, yes, yes, no, yes, no, no, no, no, no), 22, 22, 0).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, no, no, no), 23, 23, 0).
encodecodeHist(history(no, no, no, yes, yes, no, no, no, no, no), 24, 24, 0).
encodecodeHist(history(yes, no, no, yes, yes, no, no, no, no, no), 25, 25, 0).
encodecodeHist(history(no, yes, no, yes, yes, no, no, no, no, no), 26, 26, 0).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, no, no, no), 27, 27, 0).
encodecodeHist(history(no, no, yes, yes, yes, no, no, no, no, no), 28, 28, 0).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, no, no, no), 29, 29, 0).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, no, no, no), 30, 30, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, no, no, no), 31, 31, 0).
encodecodeHist(history(no, no, no, no, no, yes, no, no, no, no), 32, 32, 0).
encodecodeHist(history(yes, no, no, no, no, yes, no, no, no, no), 33, 33, 0).
encodecodeHist(history(no, yes, no, no, no, yes, no, no, no, no), 34, 34, 0).
encodecodeHist(history(yes, yes, no, no, no, yes, no, no, no, no), 35, 35, 0).
encodecodeHist(history(no, no, yes, no, no, yes, no, no, no, no), 36, 36, 0).
encodecodeHist(history(yes, no, yes, no, no, yes, no, no, no, no), 37, 37, 0).
encodecodeHist(history(no, yes, yes, no, no, yes, no, no, no, no), 38, 38, 0).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, no, no, no), 39, 39, 0).
encodecodeHist(history(no, no, no, yes, no, yes, no, no, no, no), 40, 40, 0).
encodecodeHist(history(yes, no, no, yes, no, yes, no, no, no, no), 41, 41, 0).
encodecodeHist(history(no, yes, no, yes, no, yes, no, no, no, no), 42, 42, 0).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, no, no, no), 43, 43, 0).
encodecodeHist(history(no, no, yes, yes, no, yes, no, no, no, no), 44, 44, 0).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, no, no, no), 45, 45, 0).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, no, no, no), 46, 46, 0).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, no, no, no), 47, 47, 0).
encodecodeHist(history(no, no, no, no, yes, yes, no, no, no, no), 48, 48, 0).
encodecodeHist(history(yes, no, no, no, yes, yes, no, no, no, no), 49, 49, 0).
encodecodeHist(history(no, yes, no, no, yes, yes, no, no, no, no), 50, 50, 0).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, no, no, no), 51, 51, 0).
encodecodeHist(history(no, no, yes, no, yes, yes, no, no, no, no), 52, 52, 0).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, no, no, no), 53, 53, 0).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, no, no, no), 54, 54, 0).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, no, no, no), 55, 55, 0).
encodecodeHist(history(no, no, no, yes, yes, yes, no, no, no, no), 56, 56, 0).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, no, no, no), 57, 57, 0).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, no, no, no), 58, 58, 0).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, no, no, no), 59, 59, 0).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, no, no, no), 60, 60, 0).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, no, no, no), 61, 61, 0).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, no, no, no), 62, 62, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, no, no, no), 63, 63, 0).
encodecodeHist(history(no, no, no, no, no, no, yes, no, no, no), 64, 64, 0).
encodecodeHist(history(yes, no, no, no, no, no, yes, no, no, no), 65, 65, 0).
encodecodeHist(history(no, yes, no, no, no, no, yes, no, no, no), 66, 66, 0).
encodecodeHist(history(yes, yes, no, no, no, no, yes, no, no, no), 67, 67, 0).
encodecodeHist(history(no, no, yes, no, no, no, yes, no, no, no), 68, 68, 0).
encodecodeHist(history(yes, no, yes, no, no, no, yes, no, no, no), 69, 69, 0).
encodecodeHist(history(no, yes, yes, no, no, no, yes, no, no, no), 70, 70, 0).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, no, no, no), 71, 71, 0).
encodecodeHist(history(no, no, no, yes, no, no, yes, no, no, no), 72, 72, 0).
encodecodeHist(history(yes, no, no, yes, no, no, yes, no, no, no), 73, 73, 0).
encodecodeHist(history(no, yes, no, yes, no, no, yes, no, no, no), 74, 74, 0).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, no, no, no), 75, 75, 0).
encodecodeHist(history(no, no, yes, yes, no, no, yes, no, no, no), 76, 76, 0).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, no, no, no), 77, 77, 0).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, no, no, no), 78, 78, 0).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, no, no, no), 79, 79, 0).
encodecodeHist(history(no, no, no, no, yes, no, yes, no, no, no), 80, 80, 0).
encodecodeHist(history(yes, no, no, no, yes, no, yes, no, no, no), 81, 81, 0).
encodecodeHist(history(no, yes, no, no, yes, no, yes, no, no, no), 82, 82, 0).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, no, no, no), 83, 83, 0).
encodecodeHist(history(no, no, yes, no, yes, no, yes, no, no, no), 84, 84, 0).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, no, no, no), 85, 85, 0).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, no, no, no), 86, 86, 0).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, no, no, no), 87, 87, 0).
encodecodeHist(history(no, no, no, yes, yes, no, yes, no, no, no), 88, 88, 0).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, no, no, no), 89, 89, 0).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, no, no, no), 90, 90, 0).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, no, no, no), 91, 91, 0).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, no, no, no), 92, 92, 0).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, no, no, no), 93, 93, 0).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, no, no, no), 94, 94, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, no, no, no), 95, 95, 0).
encodecodeHist(history(no, no, no, no, no, yes, yes, no, no, no), 96, 96, 0).
encodecodeHist(history(yes, no, no, no, no, yes, yes, no, no, no), 97, 97, 0).
encodecodeHist(history(no, yes, no, no, no, yes, yes, no, no, no), 98, 98, 0).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, no, no, no), 99, 99, 0).
encodecodeHist(history(no, no, yes, no, no, yes, yes, no, no, no), 100, 100, 0).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, no, no, no), 101, 101, 0).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, no, no, no), 102, 102, 0).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, no, no, no), 103, 103, 0).
encodecodeHist(history(no, no, no, yes, no, yes, yes, no, no, no), 104, 104, 0).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, no, no, no), 105, 105, 0).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, no, no, no), 106, 106, 0).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, no, no, no), 107, 107, 0).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, no, no, no), 108, 108, 0).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, no, no, no), 109, 109, 0).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, no, no, no), 110, 110, 0).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, no, no, no), 111, 111, 0).
encodecodeHist(history(no, no, no, no, yes, yes, yes, no, no, no), 112, 112, 0).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, no, no, no), 113, 113, 0).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, no, no, no), 114, 114, 0).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, no, no, no), 115, 115, 0).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, no, no, no), 116, 116, 0).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, no, no, no), 117, 117, 0).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, no, no, no), 118, 118, 0).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, no, no, no), 119, 119, 0).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, no, no, no), 120, 120, 0).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, no, no, no), 121, 121, 0).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, no, no, no), 122, 122, 0).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, no, no, no), 123, 123, 0).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, no, no, no), 124, 124, 0).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, no, no, no), 125, 125, 0).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, no, no, no), 126, 126, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, no, no, no), 127, 127, 0).
encodecodeHist(history(no, no, no, no, no, no, no, yes, no, no), 128, 128, 0).
encodecodeHist(history(yes, no, no, no, no, no, no, yes, no, no), 129, 129, 0).
encodecodeHist(history(no, yes, no, no, no, no, no, yes, no, no), 130, 130, 0).
encodecodeHist(history(yes, yes, no, no, no, no, no, yes, no, no), 131, 131, 0).
encodecodeHist(history(no, no, yes, no, no, no, no, yes, no, no), 132, 132, 0).
encodecodeHist(history(yes, no, yes, no, no, no, no, yes, no, no), 133, 133, 0).
encodecodeHist(history(no, yes, yes, no, no, no, no, yes, no, no), 134, 134, 0).
encodecodeHist(history(yes, yes, yes, no, no, no, no, yes, no, no), 135, 135, 0).
encodecodeHist(history(no, no, no, yes, no, no, no, yes, no, no), 136, 136, 0).
encodecodeHist(history(yes, no, no, yes, no, no, no, yes, no, no), 137, 137, 0).
encodecodeHist(history(no, yes, no, yes, no, no, no, yes, no, no), 138, 138, 0).
encodecodeHist(history(yes, yes, no, yes, no, no, no, yes, no, no), 139, 139, 0).
encodecodeHist(history(no, no, yes, yes, no, no, no, yes, no, no), 140, 140, 0).
encodecodeHist(history(yes, no, yes, yes, no, no, no, yes, no, no), 141, 141, 0).
encodecodeHist(history(no, yes, yes, yes, no, no, no, yes, no, no), 142, 142, 0).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, yes, no, no), 143, 143, 0).
encodecodeHist(history(no, no, no, no, yes, no, no, yes, no, no), 144, 144, 0).
encodecodeHist(history(yes, no, no, no, yes, no, no, yes, no, no), 145, 145, 0).
encodecodeHist(history(no, yes, no, no, yes, no, no, yes, no, no), 146, 146, 0).
encodecodeHist(history(yes, yes, no, no, yes, no, no, yes, no, no), 147, 147, 0).
encodecodeHist(history(no, no, yes, no, yes, no, no, yes, no, no), 148, 148, 0).
encodecodeHist(history(yes, no, yes, no, yes, no, no, yes, no, no), 149, 149, 0).
encodecodeHist(history(no, yes, yes, no, yes, no, no, yes, no, no), 150, 150, 0).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, yes, no, no), 151, 151, 0).
encodecodeHist(history(no, no, no, yes, yes, no, no, yes, no, no), 152, 152, 0).
encodecodeHist(history(yes, no, no, yes, yes, no, no, yes, no, no), 153, 153, 0).
encodecodeHist(history(no, yes, no, yes, yes, no, no, yes, no, no), 154, 154, 0).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, yes, no, no), 155, 155, 0).
encodecodeHist(history(no, no, yes, yes, yes, no, no, yes, no, no), 156, 156, 0).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, yes, no, no), 157, 157, 0).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, yes, no, no), 158, 158, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, yes, no, no), 159, 159, 0).
encodecodeHist(history(no, no, no, no, no, yes, no, yes, no, no), 160, 160, 0).
encodecodeHist(history(yes, no, no, no, no, yes, no, yes, no, no), 161, 161, 0).
encodecodeHist(history(no, yes, no, no, no, yes, no, yes, no, no), 162, 162, 0).
encodecodeHist(history(yes, yes, no, no, no, yes, no, yes, no, no), 163, 163, 0).
encodecodeHist(history(no, no, yes, no, no, yes, no, yes, no, no), 164, 164, 0).
encodecodeHist(history(yes, no, yes, no, no, yes, no, yes, no, no), 165, 165, 0).
encodecodeHist(history(no, yes, yes, no, no, yes, no, yes, no, no), 166, 166, 0).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, yes, no, no), 167, 167, 0).
encodecodeHist(history(no, no, no, yes, no, yes, no, yes, no, no), 168, 168, 0).
encodecodeHist(history(yes, no, no, yes, no, yes, no, yes, no, no), 169, 169, 0).
encodecodeHist(history(no, yes, no, yes, no, yes, no, yes, no, no), 170, 170, 0).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, yes, no, no), 171, 171, 0).
encodecodeHist(history(no, no, yes, yes, no, yes, no, yes, no, no), 172, 172, 0).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, yes, no, no), 173, 173, 0).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, yes, no, no), 174, 174, 0).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, yes, no, no), 175, 175, 0).
encodecodeHist(history(no, no, no, no, yes, yes, no, yes, no, no), 176, 176, 0).
encodecodeHist(history(yes, no, no, no, yes, yes, no, yes, no, no), 177, 177, 0).
encodecodeHist(history(no, yes, no, no, yes, yes, no, yes, no, no), 178, 178, 0).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, yes, no, no), 179, 179, 0).
encodecodeHist(history(no, no, yes, no, yes, yes, no, yes, no, no), 180, 180, 0).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, yes, no, no), 181, 181, 0).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, yes, no, no), 182, 182, 0).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, yes, no, no), 183, 183, 0).
encodecodeHist(history(no, no, no, yes, yes, yes, no, yes, no, no), 184, 184, 0).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, yes, no, no), 185, 185, 0).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, yes, no, no), 186, 186, 0).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, yes, no, no), 187, 187, 0).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, yes, no, no), 188, 188, 0).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, yes, no, no), 189, 189, 0).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, yes, no, no), 190, 190, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, yes, no, no), 191, 191, 0).
encodecodeHist(history(no, no, no, no, no, no, yes, yes, no, no), 192, 192, 0).
encodecodeHist(history(yes, no, no, no, no, no, yes, yes, no, no), 193, 193, 0).
encodecodeHist(history(no, yes, no, no, no, no, yes, yes, no, no), 194, 194, 0).
encodecodeHist(history(yes, yes, no, no, no, no, yes, yes, no, no), 195, 195, 0).
encodecodeHist(history(no, no, yes, no, no, no, yes, yes, no, no), 196, 196, 0).
encodecodeHist(history(yes, no, yes, no, no, no, yes, yes, no, no), 197, 197, 0).
encodecodeHist(history(no, yes, yes, no, no, no, yes, yes, no, no), 198, 198, 0).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, yes, no, no), 199, 199, 0).
encodecodeHist(history(no, no, no, yes, no, no, yes, yes, no, no), 200, 200, 0).
encodecodeHist(history(yes, no, no, yes, no, no, yes, yes, no, no), 201, 201, 0).
encodecodeHist(history(no, yes, no, yes, no, no, yes, yes, no, no), 202, 202, 0).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, yes, no, no), 203, 203, 0).
encodecodeHist(history(no, no, yes, yes, no, no, yes, yes, no, no), 204, 204, 0).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, yes, no, no), 205, 205, 0).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, yes, no, no), 206, 206, 0).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, yes, no, no), 207, 207, 0).
encodecodeHist(history(no, no, no, no, yes, no, yes, yes, no, no), 208, 208, 0).
encodecodeHist(history(yes, no, no, no, yes, no, yes, yes, no, no), 209, 209, 0).
encodecodeHist(history(no, yes, no, no, yes, no, yes, yes, no, no), 210, 210, 0).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, yes, no, no), 211, 211, 0).
encodecodeHist(history(no, no, yes, no, yes, no, yes, yes, no, no), 212, 212, 0).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, yes, no, no), 213, 213, 0).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, yes, no, no), 214, 214, 0).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, yes, no, no), 215, 215, 0).
encodecodeHist(history(no, no, no, yes, yes, no, yes, yes, no, no), 216, 216, 0).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, yes, no, no), 217, 217, 0).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, yes, no, no), 218, 218, 0).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, yes, no, no), 219, 219, 0).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, yes, no, no), 220, 220, 0).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, yes, no, no), 221, 221, 0).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, yes, no, no), 222, 222, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, yes, no, no), 223, 223, 0).
encodecodeHist(history(no, no, no, no, no, yes, yes, yes, no, no), 224, 224, 0).
encodecodeHist(history(yes, no, no, no, no, yes, yes, yes, no, no), 225, 225, 0).
encodecodeHist(history(no, yes, no, no, no, yes, yes, yes, no, no), 226, 226, 0).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, yes, no, no), 227, 227, 0).
encodecodeHist(history(no, no, yes, no, no, yes, yes, yes, no, no), 228, 228, 0).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, yes, no, no), 229, 229, 0).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, yes, no, no), 230, 230, 0).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, yes, no, no), 231, 231, 0).
encodecodeHist(history(no, no, no, yes, no, yes, yes, yes, no, no), 232, 232, 0).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, yes, no, no), 233, 233, 0).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, yes, no, no), 234, 234, 0).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, yes, no, no), 235, 235, 0).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, yes, no, no), 236, 236, 0).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, yes, no, no), 237, 237, 0).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, yes, no, no), 238, 238, 0).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, yes, no, no), 239, 239, 0).
encodecodeHist(history(no, no, no, no, yes, yes, yes, yes, no, no), 240, 240, 0).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, yes, no, no), 241, 241, 0).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, yes, no, no), 242, 242, 0).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, yes, no, no), 243, 243, 0).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, yes, no, no), 244, 244, 0).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, yes, no, no), 245, 245, 0).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, yes, no, no), 246, 246, 0).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, yes, no, no), 247, 247, 0).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, yes, no, no), 248, 248, 0).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, yes, no, no), 249, 249, 0).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, yes, no, no), 250, 250, 0).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, yes, no, no), 251, 251, 0).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, yes, no, no), 252, 252, 0).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, yes, no, no), 253, 253, 0).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, yes, no, no), 254, 254, 0).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, yes, no, no), 255, 255, 0).
encodecodeHist(history(no, no, no, no, no, no, no, no, yes, no), 256, 0, 1).
encodecodeHist(history(yes, no, no, no, no, no, no, no, yes, no), 257, 1, 1).
encodecodeHist(history(no, yes, no, no, no, no, no, no, yes, no), 258, 2, 1).
encodecodeHist(history(yes, yes, no, no, no, no, no, no, yes, no), 259, 3, 1).
encodecodeHist(history(no, no, yes, no, no, no, no, no, yes, no), 260, 4, 1).
encodecodeHist(history(yes, no, yes, no, no, no, no, no, yes, no), 261, 5, 1).
encodecodeHist(history(no, yes, yes, no, no, no, no, no, yes, no), 262, 6, 1).
encodecodeHist(history(yes, yes, yes, no, no, no, no, no, yes, no), 263, 7, 1).
encodecodeHist(history(no, no, no, yes, no, no, no, no, yes, no), 264, 8, 1).
encodecodeHist(history(yes, no, no, yes, no, no, no, no, yes, no), 265, 9, 1).
encodecodeHist(history(no, yes, no, yes, no, no, no, no, yes, no), 266, 10, 1).
encodecodeHist(history(yes, yes, no, yes, no, no, no, no, yes, no), 267, 11, 1).
encodecodeHist(history(no, no, yes, yes, no, no, no, no, yes, no), 268, 12, 1).
encodecodeHist(history(yes, no, yes, yes, no, no, no, no, yes, no), 269, 13, 1).
encodecodeHist(history(no, yes, yes, yes, no, no, no, no, yes, no), 270, 14, 1).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, no, yes, no), 271, 15, 1).
encodecodeHist(history(no, no, no, no, yes, no, no, no, yes, no), 272, 16, 1).
encodecodeHist(history(yes, no, no, no, yes, no, no, no, yes, no), 273, 17, 1).
encodecodeHist(history(no, yes, no, no, yes, no, no, no, yes, no), 274, 18, 1).
encodecodeHist(history(yes, yes, no, no, yes, no, no, no, yes, no), 275, 19, 1).
encodecodeHist(history(no, no, yes, no, yes, no, no, no, yes, no), 276, 20, 1).
encodecodeHist(history(yes, no, yes, no, yes, no, no, no, yes, no), 277, 21, 1).
encodecodeHist(history(no, yes, yes, no, yes, no, no, no, yes, no), 278, 22, 1).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, no, yes, no), 279, 23, 1).
encodecodeHist(history(no, no, no, yes, yes, no, no, no, yes, no), 280, 24, 1).
encodecodeHist(history(yes, no, no, yes, yes, no, no, no, yes, no), 281, 25, 1).
encodecodeHist(history(no, yes, no, yes, yes, no, no, no, yes, no), 282, 26, 1).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, no, yes, no), 283, 27, 1).
encodecodeHist(history(no, no, yes, yes, yes, no, no, no, yes, no), 284, 28, 1).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, no, yes, no), 285, 29, 1).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, no, yes, no), 286, 30, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, no, yes, no), 287, 31, 1).
encodecodeHist(history(no, no, no, no, no, yes, no, no, yes, no), 288, 32, 1).
encodecodeHist(history(yes, no, no, no, no, yes, no, no, yes, no), 289, 33, 1).
encodecodeHist(history(no, yes, no, no, no, yes, no, no, yes, no), 290, 34, 1).
encodecodeHist(history(yes, yes, no, no, no, yes, no, no, yes, no), 291, 35, 1).
encodecodeHist(history(no, no, yes, no, no, yes, no, no, yes, no), 292, 36, 1).
encodecodeHist(history(yes, no, yes, no, no, yes, no, no, yes, no), 293, 37, 1).
encodecodeHist(history(no, yes, yes, no, no, yes, no, no, yes, no), 294, 38, 1).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, no, yes, no), 295, 39, 1).
encodecodeHist(history(no, no, no, yes, no, yes, no, no, yes, no), 296, 40, 1).
encodecodeHist(history(yes, no, no, yes, no, yes, no, no, yes, no), 297, 41, 1).
encodecodeHist(history(no, yes, no, yes, no, yes, no, no, yes, no), 298, 42, 1).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, no, yes, no), 299, 43, 1).
encodecodeHist(history(no, no, yes, yes, no, yes, no, no, yes, no), 300, 44, 1).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, no, yes, no), 301, 45, 1).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, no, yes, no), 302, 46, 1).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, no, yes, no), 303, 47, 1).
encodecodeHist(history(no, no, no, no, yes, yes, no, no, yes, no), 304, 48, 1).
encodecodeHist(history(yes, no, no, no, yes, yes, no, no, yes, no), 305, 49, 1).
encodecodeHist(history(no, yes, no, no, yes, yes, no, no, yes, no), 306, 50, 1).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, no, yes, no), 307, 51, 1).
encodecodeHist(history(no, no, yes, no, yes, yes, no, no, yes, no), 308, 52, 1).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, no, yes, no), 309, 53, 1).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, no, yes, no), 310, 54, 1).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, no, yes, no), 311, 55, 1).
encodecodeHist(history(no, no, no, yes, yes, yes, no, no, yes, no), 312, 56, 1).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, no, yes, no), 313, 57, 1).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, no, yes, no), 314, 58, 1).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, no, yes, no), 315, 59, 1).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, no, yes, no), 316, 60, 1).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, no, yes, no), 317, 61, 1).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, no, yes, no), 318, 62, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, no, yes, no), 319, 63, 1).
encodecodeHist(history(no, no, no, no, no, no, yes, no, yes, no), 320, 64, 1).
encodecodeHist(history(yes, no, no, no, no, no, yes, no, yes, no), 321, 65, 1).
encodecodeHist(history(no, yes, no, no, no, no, yes, no, yes, no), 322, 66, 1).
encodecodeHist(history(yes, yes, no, no, no, no, yes, no, yes, no), 323, 67, 1).
encodecodeHist(history(no, no, yes, no, no, no, yes, no, yes, no), 324, 68, 1).
encodecodeHist(history(yes, no, yes, no, no, no, yes, no, yes, no), 325, 69, 1).
encodecodeHist(history(no, yes, yes, no, no, no, yes, no, yes, no), 326, 70, 1).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, no, yes, no), 327, 71, 1).
encodecodeHist(history(no, no, no, yes, no, no, yes, no, yes, no), 328, 72, 1).
encodecodeHist(history(yes, no, no, yes, no, no, yes, no, yes, no), 329, 73, 1).
encodecodeHist(history(no, yes, no, yes, no, no, yes, no, yes, no), 330, 74, 1).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, no, yes, no), 331, 75, 1).
encodecodeHist(history(no, no, yes, yes, no, no, yes, no, yes, no), 332, 76, 1).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, no, yes, no), 333, 77, 1).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, no, yes, no), 334, 78, 1).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, no, yes, no), 335, 79, 1).
encodecodeHist(history(no, no, no, no, yes, no, yes, no, yes, no), 336, 80, 1).
encodecodeHist(history(yes, no, no, no, yes, no, yes, no, yes, no), 337, 81, 1).
encodecodeHist(history(no, yes, no, no, yes, no, yes, no, yes, no), 338, 82, 1).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, no, yes, no), 339, 83, 1).
encodecodeHist(history(no, no, yes, no, yes, no, yes, no, yes, no), 340, 84, 1).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, no, yes, no), 341, 85, 1).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, no, yes, no), 342, 86, 1).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, no, yes, no), 343, 87, 1).
encodecodeHist(history(no, no, no, yes, yes, no, yes, no, yes, no), 344, 88, 1).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, no, yes, no), 345, 89, 1).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, no, yes, no), 346, 90, 1).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, no, yes, no), 347, 91, 1).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, no, yes, no), 348, 92, 1).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, no, yes, no), 349, 93, 1).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, no, yes, no), 350, 94, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, no, yes, no), 351, 95, 1).
encodecodeHist(history(no, no, no, no, no, yes, yes, no, yes, no), 352, 96, 1).
encodecodeHist(history(yes, no, no, no, no, yes, yes, no, yes, no), 353, 97, 1).
encodecodeHist(history(no, yes, no, no, no, yes, yes, no, yes, no), 354, 98, 1).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, no, yes, no), 355, 99, 1).
encodecodeHist(history(no, no, yes, no, no, yes, yes, no, yes, no), 356, 100, 1).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, no, yes, no), 357, 101, 1).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, no, yes, no), 358, 102, 1).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, no, yes, no), 359, 103, 1).
encodecodeHist(history(no, no, no, yes, no, yes, yes, no, yes, no), 360, 104, 1).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, no, yes, no), 361, 105, 1).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, no, yes, no), 362, 106, 1).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, no, yes, no), 363, 107, 1).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, no, yes, no), 364, 108, 1).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, no, yes, no), 365, 109, 1).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, no, yes, no), 366, 110, 1).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, no, yes, no), 367, 111, 1).
encodecodeHist(history(no, no, no, no, yes, yes, yes, no, yes, no), 368, 112, 1).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, no, yes, no), 369, 113, 1).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, no, yes, no), 370, 114, 1).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, no, yes, no), 371, 115, 1).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, no, yes, no), 372, 116, 1).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, no, yes, no), 373, 117, 1).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, no, yes, no), 374, 118, 1).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, no, yes, no), 375, 119, 1).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, no, yes, no), 376, 120, 1).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, no, yes, no), 377, 121, 1).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, no, yes, no), 378, 122, 1).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, no, yes, no), 379, 123, 1).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, no, yes, no), 380, 124, 1).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, no, yes, no), 381, 125, 1).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, no, yes, no), 382, 126, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, no, yes, no), 383, 127, 1).
encodecodeHist(history(no, no, no, no, no, no, no, yes, yes, no), 384, 128, 1).
encodecodeHist(history(yes, no, no, no, no, no, no, yes, yes, no), 385, 129, 1).
encodecodeHist(history(no, yes, no, no, no, no, no, yes, yes, no), 386, 130, 1).
encodecodeHist(history(yes, yes, no, no, no, no, no, yes, yes, no), 387, 131, 1).
encodecodeHist(history(no, no, yes, no, no, no, no, yes, yes, no), 388, 132, 1).
encodecodeHist(history(yes, no, yes, no, no, no, no, yes, yes, no), 389, 133, 1).
encodecodeHist(history(no, yes, yes, no, no, no, no, yes, yes, no), 390, 134, 1).
encodecodeHist(history(yes, yes, yes, no, no, no, no, yes, yes, no), 391, 135, 1).
encodecodeHist(history(no, no, no, yes, no, no, no, yes, yes, no), 392, 136, 1).
encodecodeHist(history(yes, no, no, yes, no, no, no, yes, yes, no), 393, 137, 1).
encodecodeHist(history(no, yes, no, yes, no, no, no, yes, yes, no), 394, 138, 1).
encodecodeHist(history(yes, yes, no, yes, no, no, no, yes, yes, no), 395, 139, 1).
encodecodeHist(history(no, no, yes, yes, no, no, no, yes, yes, no), 396, 140, 1).
encodecodeHist(history(yes, no, yes, yes, no, no, no, yes, yes, no), 397, 141, 1).
encodecodeHist(history(no, yes, yes, yes, no, no, no, yes, yes, no), 398, 142, 1).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, yes, yes, no), 399, 143, 1).
encodecodeHist(history(no, no, no, no, yes, no, no, yes, yes, no), 400, 144, 1).
encodecodeHist(history(yes, no, no, no, yes, no, no, yes, yes, no), 401, 145, 1).
encodecodeHist(history(no, yes, no, no, yes, no, no, yes, yes, no), 402, 146, 1).
encodecodeHist(history(yes, yes, no, no, yes, no, no, yes, yes, no), 403, 147, 1).
encodecodeHist(history(no, no, yes, no, yes, no, no, yes, yes, no), 404, 148, 1).
encodecodeHist(history(yes, no, yes, no, yes, no, no, yes, yes, no), 405, 149, 1).
encodecodeHist(history(no, yes, yes, no, yes, no, no, yes, yes, no), 406, 150, 1).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, yes, yes, no), 407, 151, 1).
encodecodeHist(history(no, no, no, yes, yes, no, no, yes, yes, no), 408, 152, 1).
encodecodeHist(history(yes, no, no, yes, yes, no, no, yes, yes, no), 409, 153, 1).
encodecodeHist(history(no, yes, no, yes, yes, no, no, yes, yes, no), 410, 154, 1).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, yes, yes, no), 411, 155, 1).
encodecodeHist(history(no, no, yes, yes, yes, no, no, yes, yes, no), 412, 156, 1).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, yes, yes, no), 413, 157, 1).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, yes, yes, no), 414, 158, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, yes, yes, no), 415, 159, 1).
encodecodeHist(history(no, no, no, no, no, yes, no, yes, yes, no), 416, 160, 1).
encodecodeHist(history(yes, no, no, no, no, yes, no, yes, yes, no), 417, 161, 1).
encodecodeHist(history(no, yes, no, no, no, yes, no, yes, yes, no), 418, 162, 1).
encodecodeHist(history(yes, yes, no, no, no, yes, no, yes, yes, no), 419, 163, 1).
encodecodeHist(history(no, no, yes, no, no, yes, no, yes, yes, no), 420, 164, 1).
encodecodeHist(history(yes, no, yes, no, no, yes, no, yes, yes, no), 421, 165, 1).
encodecodeHist(history(no, yes, yes, no, no, yes, no, yes, yes, no), 422, 166, 1).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, yes, yes, no), 423, 167, 1).
encodecodeHist(history(no, no, no, yes, no, yes, no, yes, yes, no), 424, 168, 1).
encodecodeHist(history(yes, no, no, yes, no, yes, no, yes, yes, no), 425, 169, 1).
encodecodeHist(history(no, yes, no, yes, no, yes, no, yes, yes, no), 426, 170, 1).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, yes, yes, no), 427, 171, 1).
encodecodeHist(history(no, no, yes, yes, no, yes, no, yes, yes, no), 428, 172, 1).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, yes, yes, no), 429, 173, 1).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, yes, yes, no), 430, 174, 1).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, yes, yes, no), 431, 175, 1).
encodecodeHist(history(no, no, no, no, yes, yes, no, yes, yes, no), 432, 176, 1).
encodecodeHist(history(yes, no, no, no, yes, yes, no, yes, yes, no), 433, 177, 1).
encodecodeHist(history(no, yes, no, no, yes, yes, no, yes, yes, no), 434, 178, 1).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, yes, yes, no), 435, 179, 1).
encodecodeHist(history(no, no, yes, no, yes, yes, no, yes, yes, no), 436, 180, 1).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, yes, yes, no), 437, 181, 1).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, yes, yes, no), 438, 182, 1).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, yes, yes, no), 439, 183, 1).
encodecodeHist(history(no, no, no, yes, yes, yes, no, yes, yes, no), 440, 184, 1).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, yes, yes, no), 441, 185, 1).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, yes, yes, no), 442, 186, 1).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, yes, yes, no), 443, 187, 1).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, yes, yes, no), 444, 188, 1).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, yes, yes, no), 445, 189, 1).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, yes, yes, no), 446, 190, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, yes, yes, no), 447, 191, 1).
encodecodeHist(history(no, no, no, no, no, no, yes, yes, yes, no), 448, 192, 1).
encodecodeHist(history(yes, no, no, no, no, no, yes, yes, yes, no), 449, 193, 1).
encodecodeHist(history(no, yes, no, no, no, no, yes, yes, yes, no), 450, 194, 1).
encodecodeHist(history(yes, yes, no, no, no, no, yes, yes, yes, no), 451, 195, 1).
encodecodeHist(history(no, no, yes, no, no, no, yes, yes, yes, no), 452, 196, 1).
encodecodeHist(history(yes, no, yes, no, no, no, yes, yes, yes, no), 453, 197, 1).
encodecodeHist(history(no, yes, yes, no, no, no, yes, yes, yes, no), 454, 198, 1).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, yes, yes, no), 455, 199, 1).
encodecodeHist(history(no, no, no, yes, no, no, yes, yes, yes, no), 456, 200, 1).
encodecodeHist(history(yes, no, no, yes, no, no, yes, yes, yes, no), 457, 201, 1).
encodecodeHist(history(no, yes, no, yes, no, no, yes, yes, yes, no), 458, 202, 1).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, yes, yes, no), 459, 203, 1).
encodecodeHist(history(no, no, yes, yes, no, no, yes, yes, yes, no), 460, 204, 1).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, yes, yes, no), 461, 205, 1).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, yes, yes, no), 462, 206, 1).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, yes, yes, no), 463, 207, 1).
encodecodeHist(history(no, no, no, no, yes, no, yes, yes, yes, no), 464, 208, 1).
encodecodeHist(history(yes, no, no, no, yes, no, yes, yes, yes, no), 465, 209, 1).
encodecodeHist(history(no, yes, no, no, yes, no, yes, yes, yes, no), 466, 210, 1).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, yes, yes, no), 467, 211, 1).
encodecodeHist(history(no, no, yes, no, yes, no, yes, yes, yes, no), 468, 212, 1).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, yes, yes, no), 469, 213, 1).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, yes, yes, no), 470, 214, 1).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, yes, yes, no), 471, 215, 1).
encodecodeHist(history(no, no, no, yes, yes, no, yes, yes, yes, no), 472, 216, 1).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, yes, yes, no), 473, 217, 1).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, yes, yes, no), 474, 218, 1).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, yes, yes, no), 475, 219, 1).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, yes, yes, no), 476, 220, 1).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, yes, yes, no), 477, 221, 1).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, yes, yes, no), 478, 222, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, yes, yes, no), 479, 223, 1).
encodecodeHist(history(no, no, no, no, no, yes, yes, yes, yes, no), 480, 224, 1).
encodecodeHist(history(yes, no, no, no, no, yes, yes, yes, yes, no), 481, 225, 1).
encodecodeHist(history(no, yes, no, no, no, yes, yes, yes, yes, no), 482, 226, 1).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, yes, yes, no), 483, 227, 1).
encodecodeHist(history(no, no, yes, no, no, yes, yes, yes, yes, no), 484, 228, 1).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, yes, yes, no), 485, 229, 1).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, yes, yes, no), 486, 230, 1).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, yes, yes, no), 487, 231, 1).
encodecodeHist(history(no, no, no, yes, no, yes, yes, yes, yes, no), 488, 232, 1).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, yes, yes, no), 489, 233, 1).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, yes, yes, no), 490, 234, 1).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, yes, yes, no), 491, 235, 1).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, yes, yes, no), 492, 236, 1).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, yes, yes, no), 493, 237, 1).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, yes, yes, no), 494, 238, 1).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, yes, yes, no), 495, 239, 1).
encodecodeHist(history(no, no, no, no, yes, yes, yes, yes, yes, no), 496, 240, 1).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, yes, yes, no), 497, 241, 1).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, yes, yes, no), 498, 242, 1).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, yes, yes, no), 499, 243, 1).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, yes, yes, no), 500, 244, 1).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, yes, yes, no), 501, 245, 1).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, yes, yes, no), 502, 246, 1).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, yes, yes, no), 503, 247, 1).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, yes, yes, no), 504, 248, 1).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, yes, yes, no), 505, 249, 1).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, yes, yes, no), 506, 250, 1).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, yes, yes, no), 507, 251, 1).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, yes, yes, no), 508, 252, 1).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, yes, yes, no), 509, 253, 1).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, yes, yes, no), 510, 254, 1).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, yes, yes, no), 511, 255, 1).
encodecodeHist(history(no, no, no, no, no, no, no, no, no, yes), 512, 0, 2).
encodecodeHist(history(yes, no, no, no, no, no, no, no, no, yes), 513, 1, 2).
encodecodeHist(history(no, yes, no, no, no, no, no, no, no, yes), 514, 2, 2).
encodecodeHist(history(yes, yes, no, no, no, no, no, no, no, yes), 515, 3, 2).
encodecodeHist(history(no, no, yes, no, no, no, no, no, no, yes), 516, 4, 2).
encodecodeHist(history(yes, no, yes, no, no, no, no, no, no, yes), 517, 5, 2).
encodecodeHist(history(no, yes, yes, no, no, no, no, no, no, yes), 518, 6, 2).
encodecodeHist(history(yes, yes, yes, no, no, no, no, no, no, yes), 519, 7, 2).
encodecodeHist(history(no, no, no, yes, no, no, no, no, no, yes), 520, 8, 2).
encodecodeHist(history(yes, no, no, yes, no, no, no, no, no, yes), 521, 9, 2).
encodecodeHist(history(no, yes, no, yes, no, no, no, no, no, yes), 522, 10, 2).
encodecodeHist(history(yes, yes, no, yes, no, no, no, no, no, yes), 523, 11, 2).
encodecodeHist(history(no, no, yes, yes, no, no, no, no, no, yes), 524, 12, 2).
encodecodeHist(history(yes, no, yes, yes, no, no, no, no, no, yes), 525, 13, 2).
encodecodeHist(history(no, yes, yes, yes, no, no, no, no, no, yes), 526, 14, 2).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, no, no, yes), 527, 15, 2).
encodecodeHist(history(no, no, no, no, yes, no, no, no, no, yes), 528, 16, 2).
encodecodeHist(history(yes, no, no, no, yes, no, no, no, no, yes), 529, 17, 2).
encodecodeHist(history(no, yes, no, no, yes, no, no, no, no, yes), 530, 18, 2).
encodecodeHist(history(yes, yes, no, no, yes, no, no, no, no, yes), 531, 19, 2).
encodecodeHist(history(no, no, yes, no, yes, no, no, no, no, yes), 532, 20, 2).
encodecodeHist(history(yes, no, yes, no, yes, no, no, no, no, yes), 533, 21, 2).
encodecodeHist(history(no, yes, yes, no, yes, no, no, no, no, yes), 534, 22, 2).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, no, no, yes), 535, 23, 2).
encodecodeHist(history(no, no, no, yes, yes, no, no, no, no, yes), 536, 24, 2).
encodecodeHist(history(yes, no, no, yes, yes, no, no, no, no, yes), 537, 25, 2).
encodecodeHist(history(no, yes, no, yes, yes, no, no, no, no, yes), 538, 26, 2).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, no, no, yes), 539, 27, 2).
encodecodeHist(history(no, no, yes, yes, yes, no, no, no, no, yes), 540, 28, 2).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, no, no, yes), 541, 29, 2).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, no, no, yes), 542, 30, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, no, no, yes), 543, 31, 2).
encodecodeHist(history(no, no, no, no, no, yes, no, no, no, yes), 544, 32, 2).
encodecodeHist(history(yes, no, no, no, no, yes, no, no, no, yes), 545, 33, 2).
encodecodeHist(history(no, yes, no, no, no, yes, no, no, no, yes), 546, 34, 2).
encodecodeHist(history(yes, yes, no, no, no, yes, no, no, no, yes), 547, 35, 2).
encodecodeHist(history(no, no, yes, no, no, yes, no, no, no, yes), 548, 36, 2).
encodecodeHist(history(yes, no, yes, no, no, yes, no, no, no, yes), 549, 37, 2).
encodecodeHist(history(no, yes, yes, no, no, yes, no, no, no, yes), 550, 38, 2).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, no, no, yes), 551, 39, 2).
encodecodeHist(history(no, no, no, yes, no, yes, no, no, no, yes), 552, 40, 2).
encodecodeHist(history(yes, no, no, yes, no, yes, no, no, no, yes), 553, 41, 2).
encodecodeHist(history(no, yes, no, yes, no, yes, no, no, no, yes), 554, 42, 2).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, no, no, yes), 555, 43, 2).
encodecodeHist(history(no, no, yes, yes, no, yes, no, no, no, yes), 556, 44, 2).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, no, no, yes), 557, 45, 2).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, no, no, yes), 558, 46, 2).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, no, no, yes), 559, 47, 2).
encodecodeHist(history(no, no, no, no, yes, yes, no, no, no, yes), 560, 48, 2).
encodecodeHist(history(yes, no, no, no, yes, yes, no, no, no, yes), 561, 49, 2).
encodecodeHist(history(no, yes, no, no, yes, yes, no, no, no, yes), 562, 50, 2).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, no, no, yes), 563, 51, 2).
encodecodeHist(history(no, no, yes, no, yes, yes, no, no, no, yes), 564, 52, 2).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, no, no, yes), 565, 53, 2).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, no, no, yes), 566, 54, 2).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, no, no, yes), 567, 55, 2).
encodecodeHist(history(no, no, no, yes, yes, yes, no, no, no, yes), 568, 56, 2).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, no, no, yes), 569, 57, 2).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, no, no, yes), 570, 58, 2).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, no, no, yes), 571, 59, 2).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, no, no, yes), 572, 60, 2).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, no, no, yes), 573, 61, 2).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, no, no, yes), 574, 62, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, no, no, yes), 575, 63, 2).
encodecodeHist(history(no, no, no, no, no, no, yes, no, no, yes), 576, 64, 2).
encodecodeHist(history(yes, no, no, no, no, no, yes, no, no, yes), 577, 65, 2).
encodecodeHist(history(no, yes, no, no, no, no, yes, no, no, yes), 578, 66, 2).
encodecodeHist(history(yes, yes, no, no, no, no, yes, no, no, yes), 579, 67, 2).
encodecodeHist(history(no, no, yes, no, no, no, yes, no, no, yes), 580, 68, 2).
encodecodeHist(history(yes, no, yes, no, no, no, yes, no, no, yes), 581, 69, 2).
encodecodeHist(history(no, yes, yes, no, no, no, yes, no, no, yes), 582, 70, 2).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, no, no, yes), 583, 71, 2).
encodecodeHist(history(no, no, no, yes, no, no, yes, no, no, yes), 584, 72, 2).
encodecodeHist(history(yes, no, no, yes, no, no, yes, no, no, yes), 585, 73, 2).
encodecodeHist(history(no, yes, no, yes, no, no, yes, no, no, yes), 586, 74, 2).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, no, no, yes), 587, 75, 2).
encodecodeHist(history(no, no, yes, yes, no, no, yes, no, no, yes), 588, 76, 2).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, no, no, yes), 589, 77, 2).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, no, no, yes), 590, 78, 2).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, no, no, yes), 591, 79, 2).
encodecodeHist(history(no, no, no, no, yes, no, yes, no, no, yes), 592, 80, 2).
encodecodeHist(history(yes, no, no, no, yes, no, yes, no, no, yes), 593, 81, 2).
encodecodeHist(history(no, yes, no, no, yes, no, yes, no, no, yes), 594, 82, 2).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, no, no, yes), 595, 83, 2).
encodecodeHist(history(no, no, yes, no, yes, no, yes, no, no, yes), 596, 84, 2).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, no, no, yes), 597, 85, 2).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, no, no, yes), 598, 86, 2).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, no, no, yes), 599, 87, 2).
encodecodeHist(history(no, no, no, yes, yes, no, yes, no, no, yes), 600, 88, 2).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, no, no, yes), 601, 89, 2).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, no, no, yes), 602, 90, 2).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, no, no, yes), 603, 91, 2).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, no, no, yes), 604, 92, 2).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, no, no, yes), 605, 93, 2).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, no, no, yes), 606, 94, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, no, no, yes), 607, 95, 2).
encodecodeHist(history(no, no, no, no, no, yes, yes, no, no, yes), 608, 96, 2).
encodecodeHist(history(yes, no, no, no, no, yes, yes, no, no, yes), 609, 97, 2).
encodecodeHist(history(no, yes, no, no, no, yes, yes, no, no, yes), 610, 98, 2).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, no, no, yes), 611, 99, 2).
encodecodeHist(history(no, no, yes, no, no, yes, yes, no, no, yes), 612, 100, 2).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, no, no, yes), 613, 101, 2).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, no, no, yes), 614, 102, 2).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, no, no, yes), 615, 103, 2).
encodecodeHist(history(no, no, no, yes, no, yes, yes, no, no, yes), 616, 104, 2).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, no, no, yes), 617, 105, 2).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, no, no, yes), 618, 106, 2).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, no, no, yes), 619, 107, 2).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, no, no, yes), 620, 108, 2).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, no, no, yes), 621, 109, 2).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, no, no, yes), 622, 110, 2).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, no, no, yes), 623, 111, 2).
encodecodeHist(history(no, no, no, no, yes, yes, yes, no, no, yes), 624, 112, 2).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, no, no, yes), 625, 113, 2).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, no, no, yes), 626, 114, 2).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, no, no, yes), 627, 115, 2).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, no, no, yes), 628, 116, 2).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, no, no, yes), 629, 117, 2).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, no, no, yes), 630, 118, 2).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, no, no, yes), 631, 119, 2).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, no, no, yes), 632, 120, 2).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, no, no, yes), 633, 121, 2).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, no, no, yes), 634, 122, 2).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, no, no, yes), 635, 123, 2).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, no, no, yes), 636, 124, 2).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, no, no, yes), 637, 125, 2).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, no, no, yes), 638, 126, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, no, no, yes), 639, 127, 2).
encodecodeHist(history(no, no, no, no, no, no, no, yes, no, yes), 640, 128, 2).
encodecodeHist(history(yes, no, no, no, no, no, no, yes, no, yes), 641, 129, 2).
encodecodeHist(history(no, yes, no, no, no, no, no, yes, no, yes), 642, 130, 2).
encodecodeHist(history(yes, yes, no, no, no, no, no, yes, no, yes), 643, 131, 2).
encodecodeHist(history(no, no, yes, no, no, no, no, yes, no, yes), 644, 132, 2).
encodecodeHist(history(yes, no, yes, no, no, no, no, yes, no, yes), 645, 133, 2).
encodecodeHist(history(no, yes, yes, no, no, no, no, yes, no, yes), 646, 134, 2).
encodecodeHist(history(yes, yes, yes, no, no, no, no, yes, no, yes), 647, 135, 2).
encodecodeHist(history(no, no, no, yes, no, no, no, yes, no, yes), 648, 136, 2).
encodecodeHist(history(yes, no, no, yes, no, no, no, yes, no, yes), 649, 137, 2).
encodecodeHist(history(no, yes, no, yes, no, no, no, yes, no, yes), 650, 138, 2).
encodecodeHist(history(yes, yes, no, yes, no, no, no, yes, no, yes), 651, 139, 2).
encodecodeHist(history(no, no, yes, yes, no, no, no, yes, no, yes), 652, 140, 2).
encodecodeHist(history(yes, no, yes, yes, no, no, no, yes, no, yes), 653, 141, 2).
encodecodeHist(history(no, yes, yes, yes, no, no, no, yes, no, yes), 654, 142, 2).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, yes, no, yes), 655, 143, 2).
encodecodeHist(history(no, no, no, no, yes, no, no, yes, no, yes), 656, 144, 2).
encodecodeHist(history(yes, no, no, no, yes, no, no, yes, no, yes), 657, 145, 2).
encodecodeHist(history(no, yes, no, no, yes, no, no, yes, no, yes), 658, 146, 2).
encodecodeHist(history(yes, yes, no, no, yes, no, no, yes, no, yes), 659, 147, 2).
encodecodeHist(history(no, no, yes, no, yes, no, no, yes, no, yes), 660, 148, 2).
encodecodeHist(history(yes, no, yes, no, yes, no, no, yes, no, yes), 661, 149, 2).
encodecodeHist(history(no, yes, yes, no, yes, no, no, yes, no, yes), 662, 150, 2).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, yes, no, yes), 663, 151, 2).
encodecodeHist(history(no, no, no, yes, yes, no, no, yes, no, yes), 664, 152, 2).
encodecodeHist(history(yes, no, no, yes, yes, no, no, yes, no, yes), 665, 153, 2).
encodecodeHist(history(no, yes, no, yes, yes, no, no, yes, no, yes), 666, 154, 2).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, yes, no, yes), 667, 155, 2).
encodecodeHist(history(no, no, yes, yes, yes, no, no, yes, no, yes), 668, 156, 2).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, yes, no, yes), 669, 157, 2).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, yes, no, yes), 670, 158, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, yes, no, yes), 671, 159, 2).
encodecodeHist(history(no, no, no, no, no, yes, no, yes, no, yes), 672, 160, 2).
encodecodeHist(history(yes, no, no, no, no, yes, no, yes, no, yes), 673, 161, 2).
encodecodeHist(history(no, yes, no, no, no, yes, no, yes, no, yes), 674, 162, 2).
encodecodeHist(history(yes, yes, no, no, no, yes, no, yes, no, yes), 675, 163, 2).
encodecodeHist(history(no, no, yes, no, no, yes, no, yes, no, yes), 676, 164, 2).
encodecodeHist(history(yes, no, yes, no, no, yes, no, yes, no, yes), 677, 165, 2).
encodecodeHist(history(no, yes, yes, no, no, yes, no, yes, no, yes), 678, 166, 2).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, yes, no, yes), 679, 167, 2).
encodecodeHist(history(no, no, no, yes, no, yes, no, yes, no, yes), 680, 168, 2).
encodecodeHist(history(yes, no, no, yes, no, yes, no, yes, no, yes), 681, 169, 2).
encodecodeHist(history(no, yes, no, yes, no, yes, no, yes, no, yes), 682, 170, 2).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, yes, no, yes), 683, 171, 2).
encodecodeHist(history(no, no, yes, yes, no, yes, no, yes, no, yes), 684, 172, 2).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, yes, no, yes), 685, 173, 2).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, yes, no, yes), 686, 174, 2).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, yes, no, yes), 687, 175, 2).
encodecodeHist(history(no, no, no, no, yes, yes, no, yes, no, yes), 688, 176, 2).
encodecodeHist(history(yes, no, no, no, yes, yes, no, yes, no, yes), 689, 177, 2).
encodecodeHist(history(no, yes, no, no, yes, yes, no, yes, no, yes), 690, 178, 2).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, yes, no, yes), 691, 179, 2).
encodecodeHist(history(no, no, yes, no, yes, yes, no, yes, no, yes), 692, 180, 2).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, yes, no, yes), 693, 181, 2).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, yes, no, yes), 694, 182, 2).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, yes, no, yes), 695, 183, 2).
encodecodeHist(history(no, no, no, yes, yes, yes, no, yes, no, yes), 696, 184, 2).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, yes, no, yes), 697, 185, 2).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, yes, no, yes), 698, 186, 2).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, yes, no, yes), 699, 187, 2).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, yes, no, yes), 700, 188, 2).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, yes, no, yes), 701, 189, 2).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, yes, no, yes), 702, 190, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, yes, no, yes), 703, 191, 2).
encodecodeHist(history(no, no, no, no, no, no, yes, yes, no, yes), 704, 192, 2).
encodecodeHist(history(yes, no, no, no, no, no, yes, yes, no, yes), 705, 193, 2).
encodecodeHist(history(no, yes, no, no, no, no, yes, yes, no, yes), 706, 194, 2).
encodecodeHist(history(yes, yes, no, no, no, no, yes, yes, no, yes), 707, 195, 2).
encodecodeHist(history(no, no, yes, no, no, no, yes, yes, no, yes), 708, 196, 2).
encodecodeHist(history(yes, no, yes, no, no, no, yes, yes, no, yes), 709, 197, 2).
encodecodeHist(history(no, yes, yes, no, no, no, yes, yes, no, yes), 710, 198, 2).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, yes, no, yes), 711, 199, 2).
encodecodeHist(history(no, no, no, yes, no, no, yes, yes, no, yes), 712, 200, 2).
encodecodeHist(history(yes, no, no, yes, no, no, yes, yes, no, yes), 713, 201, 2).
encodecodeHist(history(no, yes, no, yes, no, no, yes, yes, no, yes), 714, 202, 2).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, yes, no, yes), 715, 203, 2).
encodecodeHist(history(no, no, yes, yes, no, no, yes, yes, no, yes), 716, 204, 2).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, yes, no, yes), 717, 205, 2).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, yes, no, yes), 718, 206, 2).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, yes, no, yes), 719, 207, 2).
encodecodeHist(history(no, no, no, no, yes, no, yes, yes, no, yes), 720, 208, 2).
encodecodeHist(history(yes, no, no, no, yes, no, yes, yes, no, yes), 721, 209, 2).
encodecodeHist(history(no, yes, no, no, yes, no, yes, yes, no, yes), 722, 210, 2).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, yes, no, yes), 723, 211, 2).
encodecodeHist(history(no, no, yes, no, yes, no, yes, yes, no, yes), 724, 212, 2).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, yes, no, yes), 725, 213, 2).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, yes, no, yes), 726, 214, 2).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, yes, no, yes), 727, 215, 2).
encodecodeHist(history(no, no, no, yes, yes, no, yes, yes, no, yes), 728, 216, 2).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, yes, no, yes), 729, 217, 2).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, yes, no, yes), 730, 218, 2).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, yes, no, yes), 731, 219, 2).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, yes, no, yes), 732, 220, 2).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, yes, no, yes), 733, 221, 2).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, yes, no, yes), 734, 222, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, yes, no, yes), 735, 223, 2).
encodecodeHist(history(no, no, no, no, no, yes, yes, yes, no, yes), 736, 224, 2).
encodecodeHist(history(yes, no, no, no, no, yes, yes, yes, no, yes), 737, 225, 2).
encodecodeHist(history(no, yes, no, no, no, yes, yes, yes, no, yes), 738, 226, 2).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, yes, no, yes), 739, 227, 2).
encodecodeHist(history(no, no, yes, no, no, yes, yes, yes, no, yes), 740, 228, 2).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, yes, no, yes), 741, 229, 2).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, yes, no, yes), 742, 230, 2).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, yes, no, yes), 743, 231, 2).
encodecodeHist(history(no, no, no, yes, no, yes, yes, yes, no, yes), 744, 232, 2).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, yes, no, yes), 745, 233, 2).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, yes, no, yes), 746, 234, 2).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, yes, no, yes), 747, 235, 2).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, yes, no, yes), 748, 236, 2).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, yes, no, yes), 749, 237, 2).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, yes, no, yes), 750, 238, 2).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, yes, no, yes), 751, 239, 2).
encodecodeHist(history(no, no, no, no, yes, yes, yes, yes, no, yes), 752, 240, 2).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, yes, no, yes), 753, 241, 2).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, yes, no, yes), 754, 242, 2).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, yes, no, yes), 755, 243, 2).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, yes, no, yes), 756, 244, 2).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, yes, no, yes), 757, 245, 2).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, yes, no, yes), 758, 246, 2).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, yes, no, yes), 759, 247, 2).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, yes, no, yes), 760, 248, 2).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, yes, no, yes), 761, 249, 2).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, yes, no, yes), 762, 250, 2).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, yes, no, yes), 763, 251, 2).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, yes, no, yes), 764, 252, 2).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, yes, no, yes), 765, 253, 2).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, yes, no, yes), 766, 254, 2).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, yes, no, yes), 767, 255, 2).
encodecodeHist(history(no, no, no, no, no, no, no, no, yes, yes), 768, 0, 3).
encodecodeHist(history(yes, no, no, no, no, no, no, no, yes, yes), 769, 1, 3).
encodecodeHist(history(no, yes, no, no, no, no, no, no, yes, yes), 770, 2, 3).
encodecodeHist(history(yes, yes, no, no, no, no, no, no, yes, yes), 771, 3, 3).
encodecodeHist(history(no, no, yes, no, no, no, no, no, yes, yes), 772, 4, 3).
encodecodeHist(history(yes, no, yes, no, no, no, no, no, yes, yes), 773, 5, 3).
encodecodeHist(history(no, yes, yes, no, no, no, no, no, yes, yes), 774, 6, 3).
encodecodeHist(history(yes, yes, yes, no, no, no, no, no, yes, yes), 775, 7, 3).
encodecodeHist(history(no, no, no, yes, no, no, no, no, yes, yes), 776, 8, 3).
encodecodeHist(history(yes, no, no, yes, no, no, no, no, yes, yes), 777, 9, 3).
encodecodeHist(history(no, yes, no, yes, no, no, no, no, yes, yes), 778, 10, 3).
encodecodeHist(history(yes, yes, no, yes, no, no, no, no, yes, yes), 779, 11, 3).
encodecodeHist(history(no, no, yes, yes, no, no, no, no, yes, yes), 780, 12, 3).
encodecodeHist(history(yes, no, yes, yes, no, no, no, no, yes, yes), 781, 13, 3).
encodecodeHist(history(no, yes, yes, yes, no, no, no, no, yes, yes), 782, 14, 3).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, no, yes, yes), 783, 15, 3).
encodecodeHist(history(no, no, no, no, yes, no, no, no, yes, yes), 784, 16, 3).
encodecodeHist(history(yes, no, no, no, yes, no, no, no, yes, yes), 785, 17, 3).
encodecodeHist(history(no, yes, no, no, yes, no, no, no, yes, yes), 786, 18, 3).
encodecodeHist(history(yes, yes, no, no, yes, no, no, no, yes, yes), 787, 19, 3).
encodecodeHist(history(no, no, yes, no, yes, no, no, no, yes, yes), 788, 20, 3).
encodecodeHist(history(yes, no, yes, no, yes, no, no, no, yes, yes), 789, 21, 3).
encodecodeHist(history(no, yes, yes, no, yes, no, no, no, yes, yes), 790, 22, 3).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, no, yes, yes), 791, 23, 3).
encodecodeHist(history(no, no, no, yes, yes, no, no, no, yes, yes), 792, 24, 3).
encodecodeHist(history(yes, no, no, yes, yes, no, no, no, yes, yes), 793, 25, 3).
encodecodeHist(history(no, yes, no, yes, yes, no, no, no, yes, yes), 794, 26, 3).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, no, yes, yes), 795, 27, 3).
encodecodeHist(history(no, no, yes, yes, yes, no, no, no, yes, yes), 796, 28, 3).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, no, yes, yes), 797, 29, 3).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, no, yes, yes), 798, 30, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, no, yes, yes), 799, 31, 3).
encodecodeHist(history(no, no, no, no, no, yes, no, no, yes, yes), 800, 32, 3).
encodecodeHist(history(yes, no, no, no, no, yes, no, no, yes, yes), 801, 33, 3).
encodecodeHist(history(no, yes, no, no, no, yes, no, no, yes, yes), 802, 34, 3).
encodecodeHist(history(yes, yes, no, no, no, yes, no, no, yes, yes), 803, 35, 3).
encodecodeHist(history(no, no, yes, no, no, yes, no, no, yes, yes), 804, 36, 3).
encodecodeHist(history(yes, no, yes, no, no, yes, no, no, yes, yes), 805, 37, 3).
encodecodeHist(history(no, yes, yes, no, no, yes, no, no, yes, yes), 806, 38, 3).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, no, yes, yes), 807, 39, 3).
encodecodeHist(history(no, no, no, yes, no, yes, no, no, yes, yes), 808, 40, 3).
encodecodeHist(history(yes, no, no, yes, no, yes, no, no, yes, yes), 809, 41, 3).
encodecodeHist(history(no, yes, no, yes, no, yes, no, no, yes, yes), 810, 42, 3).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, no, yes, yes), 811, 43, 3).
encodecodeHist(history(no, no, yes, yes, no, yes, no, no, yes, yes), 812, 44, 3).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, no, yes, yes), 813, 45, 3).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, no, yes, yes), 814, 46, 3).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, no, yes, yes), 815, 47, 3).
encodecodeHist(history(no, no, no, no, yes, yes, no, no, yes, yes), 816, 48, 3).
encodecodeHist(history(yes, no, no, no, yes, yes, no, no, yes, yes), 817, 49, 3).
encodecodeHist(history(no, yes, no, no, yes, yes, no, no, yes, yes), 818, 50, 3).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, no, yes, yes), 819, 51, 3).
encodecodeHist(history(no, no, yes, no, yes, yes, no, no, yes, yes), 820, 52, 3).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, no, yes, yes), 821, 53, 3).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, no, yes, yes), 822, 54, 3).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, no, yes, yes), 823, 55, 3).
encodecodeHist(history(no, no, no, yes, yes, yes, no, no, yes, yes), 824, 56, 3).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, no, yes, yes), 825, 57, 3).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, no, yes, yes), 826, 58, 3).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, no, yes, yes), 827, 59, 3).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, no, yes, yes), 828, 60, 3).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, no, yes, yes), 829, 61, 3).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, no, yes, yes), 830, 62, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, no, yes, yes), 831, 63, 3).
encodecodeHist(history(no, no, no, no, no, no, yes, no, yes, yes), 832, 64, 3).
encodecodeHist(history(yes, no, no, no, no, no, yes, no, yes, yes), 833, 65, 3).
encodecodeHist(history(no, yes, no, no, no, no, yes, no, yes, yes), 834, 66, 3).
encodecodeHist(history(yes, yes, no, no, no, no, yes, no, yes, yes), 835, 67, 3).
encodecodeHist(history(no, no, yes, no, no, no, yes, no, yes, yes), 836, 68, 3).
encodecodeHist(history(yes, no, yes, no, no, no, yes, no, yes, yes), 837, 69, 3).
encodecodeHist(history(no, yes, yes, no, no, no, yes, no, yes, yes), 838, 70, 3).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, no, yes, yes), 839, 71, 3).
encodecodeHist(history(no, no, no, yes, no, no, yes, no, yes, yes), 840, 72, 3).
encodecodeHist(history(yes, no, no, yes, no, no, yes, no, yes, yes), 841, 73, 3).
encodecodeHist(history(no, yes, no, yes, no, no, yes, no, yes, yes), 842, 74, 3).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, no, yes, yes), 843, 75, 3).
encodecodeHist(history(no, no, yes, yes, no, no, yes, no, yes, yes), 844, 76, 3).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, no, yes, yes), 845, 77, 3).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, no, yes, yes), 846, 78, 3).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, no, yes, yes), 847, 79, 3).
encodecodeHist(history(no, no, no, no, yes, no, yes, no, yes, yes), 848, 80, 3).
encodecodeHist(history(yes, no, no, no, yes, no, yes, no, yes, yes), 849, 81, 3).
encodecodeHist(history(no, yes, no, no, yes, no, yes, no, yes, yes), 850, 82, 3).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, no, yes, yes), 851, 83, 3).
encodecodeHist(history(no, no, yes, no, yes, no, yes, no, yes, yes), 852, 84, 3).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, no, yes, yes), 853, 85, 3).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, no, yes, yes), 854, 86, 3).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, no, yes, yes), 855, 87, 3).
encodecodeHist(history(no, no, no, yes, yes, no, yes, no, yes, yes), 856, 88, 3).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, no, yes, yes), 857, 89, 3).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, no, yes, yes), 858, 90, 3).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, no, yes, yes), 859, 91, 3).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, no, yes, yes), 860, 92, 3).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, no, yes, yes), 861, 93, 3).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, no, yes, yes), 862, 94, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, no, yes, yes), 863, 95, 3).
encodecodeHist(history(no, no, no, no, no, yes, yes, no, yes, yes), 864, 96, 3).
encodecodeHist(history(yes, no, no, no, no, yes, yes, no, yes, yes), 865, 97, 3).
encodecodeHist(history(no, yes, no, no, no, yes, yes, no, yes, yes), 866, 98, 3).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, no, yes, yes), 867, 99, 3).
encodecodeHist(history(no, no, yes, no, no, yes, yes, no, yes, yes), 868, 100, 3).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, no, yes, yes), 869, 101, 3).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, no, yes, yes), 870, 102, 3).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, no, yes, yes), 871, 103, 3).
encodecodeHist(history(no, no, no, yes, no, yes, yes, no, yes, yes), 872, 104, 3).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, no, yes, yes), 873, 105, 3).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, no, yes, yes), 874, 106, 3).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, no, yes, yes), 875, 107, 3).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, no, yes, yes), 876, 108, 3).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, no, yes, yes), 877, 109, 3).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, no, yes, yes), 878, 110, 3).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, no, yes, yes), 879, 111, 3).
encodecodeHist(history(no, no, no, no, yes, yes, yes, no, yes, yes), 880, 112, 3).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, no, yes, yes), 881, 113, 3).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, no, yes, yes), 882, 114, 3).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, no, yes, yes), 883, 115, 3).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, no, yes, yes), 884, 116, 3).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, no, yes, yes), 885, 117, 3).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, no, yes, yes), 886, 118, 3).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, no, yes, yes), 887, 119, 3).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, no, yes, yes), 888, 120, 3).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, no, yes, yes), 889, 121, 3).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, no, yes, yes), 890, 122, 3).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, no, yes, yes), 891, 123, 3).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, no, yes, yes), 892, 124, 3).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, no, yes, yes), 893, 125, 3).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, no, yes, yes), 894, 126, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, no, yes, yes), 895, 127, 3).
encodecodeHist(history(no, no, no, no, no, no, no, yes, yes, yes), 896, 128, 3).
encodecodeHist(history(yes, no, no, no, no, no, no, yes, yes, yes), 897, 129, 3).
encodecodeHist(history(no, yes, no, no, no, no, no, yes, yes, yes), 898, 130, 3).
encodecodeHist(history(yes, yes, no, no, no, no, no, yes, yes, yes), 899, 131, 3).
encodecodeHist(history(no, no, yes, no, no, no, no, yes, yes, yes), 900, 132, 3).
encodecodeHist(history(yes, no, yes, no, no, no, no, yes, yes, yes), 901, 133, 3).
encodecodeHist(history(no, yes, yes, no, no, no, no, yes, yes, yes), 902, 134, 3).
encodecodeHist(history(yes, yes, yes, no, no, no, no, yes, yes, yes), 903, 135, 3).
encodecodeHist(history(no, no, no, yes, no, no, no, yes, yes, yes), 904, 136, 3).
encodecodeHist(history(yes, no, no, yes, no, no, no, yes, yes, yes), 905, 137, 3).
encodecodeHist(history(no, yes, no, yes, no, no, no, yes, yes, yes), 906, 138, 3).
encodecodeHist(history(yes, yes, no, yes, no, no, no, yes, yes, yes), 907, 139, 3).
encodecodeHist(history(no, no, yes, yes, no, no, no, yes, yes, yes), 908, 140, 3).
encodecodeHist(history(yes, no, yes, yes, no, no, no, yes, yes, yes), 909, 141, 3).
encodecodeHist(history(no, yes, yes, yes, no, no, no, yes, yes, yes), 910, 142, 3).
encodecodeHist(history(yes, yes, yes, yes, no, no, no, yes, yes, yes), 911, 143, 3).
encodecodeHist(history(no, no, no, no, yes, no, no, yes, yes, yes), 912, 144, 3).
encodecodeHist(history(yes, no, no, no, yes, no, no, yes, yes, yes), 913, 145, 3).
encodecodeHist(history(no, yes, no, no, yes, no, no, yes, yes, yes), 914, 146, 3).
encodecodeHist(history(yes, yes, no, no, yes, no, no, yes, yes, yes), 915, 147, 3).
encodecodeHist(history(no, no, yes, no, yes, no, no, yes, yes, yes), 916, 148, 3).
encodecodeHist(history(yes, no, yes, no, yes, no, no, yes, yes, yes), 917, 149, 3).
encodecodeHist(history(no, yes, yes, no, yes, no, no, yes, yes, yes), 918, 150, 3).
encodecodeHist(history(yes, yes, yes, no, yes, no, no, yes, yes, yes), 919, 151, 3).
encodecodeHist(history(no, no, no, yes, yes, no, no, yes, yes, yes), 920, 152, 3).
encodecodeHist(history(yes, no, no, yes, yes, no, no, yes, yes, yes), 921, 153, 3).
encodecodeHist(history(no, yes, no, yes, yes, no, no, yes, yes, yes), 922, 154, 3).
encodecodeHist(history(yes, yes, no, yes, yes, no, no, yes, yes, yes), 923, 155, 3).
encodecodeHist(history(no, no, yes, yes, yes, no, no, yes, yes, yes), 924, 156, 3).
encodecodeHist(history(yes, no, yes, yes, yes, no, no, yes, yes, yes), 925, 157, 3).
encodecodeHist(history(no, yes, yes, yes, yes, no, no, yes, yes, yes), 926, 158, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, no, no, yes, yes, yes), 927, 159, 3).
encodecodeHist(history(no, no, no, no, no, yes, no, yes, yes, yes), 928, 160, 3).
encodecodeHist(history(yes, no, no, no, no, yes, no, yes, yes, yes), 929, 161, 3).
encodecodeHist(history(no, yes, no, no, no, yes, no, yes, yes, yes), 930, 162, 3).
encodecodeHist(history(yes, yes, no, no, no, yes, no, yes, yes, yes), 931, 163, 3).
encodecodeHist(history(no, no, yes, no, no, yes, no, yes, yes, yes), 932, 164, 3).
encodecodeHist(history(yes, no, yes, no, no, yes, no, yes, yes, yes), 933, 165, 3).
encodecodeHist(history(no, yes, yes, no, no, yes, no, yes, yes, yes), 934, 166, 3).
encodecodeHist(history(yes, yes, yes, no, no, yes, no, yes, yes, yes), 935, 167, 3).
encodecodeHist(history(no, no, no, yes, no, yes, no, yes, yes, yes), 936, 168, 3).
encodecodeHist(history(yes, no, no, yes, no, yes, no, yes, yes, yes), 937, 169, 3).
encodecodeHist(history(no, yes, no, yes, no, yes, no, yes, yes, yes), 938, 170, 3).
encodecodeHist(history(yes, yes, no, yes, no, yes, no, yes, yes, yes), 939, 171, 3).
encodecodeHist(history(no, no, yes, yes, no, yes, no, yes, yes, yes), 940, 172, 3).
encodecodeHist(history(yes, no, yes, yes, no, yes, no, yes, yes, yes), 941, 173, 3).
encodecodeHist(history(no, yes, yes, yes, no, yes, no, yes, yes, yes), 942, 174, 3).
encodecodeHist(history(yes, yes, yes, yes, no, yes, no, yes, yes, yes), 943, 175, 3).
encodecodeHist(history(no, no, no, no, yes, yes, no, yes, yes, yes), 944, 176, 3).
encodecodeHist(history(yes, no, no, no, yes, yes, no, yes, yes, yes), 945, 177, 3).
encodecodeHist(history(no, yes, no, no, yes, yes, no, yes, yes, yes), 946, 178, 3).
encodecodeHist(history(yes, yes, no, no, yes, yes, no, yes, yes, yes), 947, 179, 3).
encodecodeHist(history(no, no, yes, no, yes, yes, no, yes, yes, yes), 948, 180, 3).
encodecodeHist(history(yes, no, yes, no, yes, yes, no, yes, yes, yes), 949, 181, 3).
encodecodeHist(history(no, yes, yes, no, yes, yes, no, yes, yes, yes), 950, 182, 3).
encodecodeHist(history(yes, yes, yes, no, yes, yes, no, yes, yes, yes), 951, 183, 3).
encodecodeHist(history(no, no, no, yes, yes, yes, no, yes, yes, yes), 952, 184, 3).
encodecodeHist(history(yes, no, no, yes, yes, yes, no, yes, yes, yes), 953, 185, 3).
encodecodeHist(history(no, yes, no, yes, yes, yes, no, yes, yes, yes), 954, 186, 3).
encodecodeHist(history(yes, yes, no, yes, yes, yes, no, yes, yes, yes), 955, 187, 3).
encodecodeHist(history(no, no, yes, yes, yes, yes, no, yes, yes, yes), 956, 188, 3).
encodecodeHist(history(yes, no, yes, yes, yes, yes, no, yes, yes, yes), 957, 189, 3).
encodecodeHist(history(no, yes, yes, yes, yes, yes, no, yes, yes, yes), 958, 190, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, no, yes, yes, yes), 959, 191, 3).
encodecodeHist(history(no, no, no, no, no, no, yes, yes, yes, yes), 960, 192, 3).
encodecodeHist(history(yes, no, no, no, no, no, yes, yes, yes, yes), 961, 193, 3).
encodecodeHist(history(no, yes, no, no, no, no, yes, yes, yes, yes), 962, 194, 3).
encodecodeHist(history(yes, yes, no, no, no, no, yes, yes, yes, yes), 963, 195, 3).
encodecodeHist(history(no, no, yes, no, no, no, yes, yes, yes, yes), 964, 196, 3).
encodecodeHist(history(yes, no, yes, no, no, no, yes, yes, yes, yes), 965, 197, 3).
encodecodeHist(history(no, yes, yes, no, no, no, yes, yes, yes, yes), 966, 198, 3).
encodecodeHist(history(yes, yes, yes, no, no, no, yes, yes, yes, yes), 967, 199, 3).
encodecodeHist(history(no, no, no, yes, no, no, yes, yes, yes, yes), 968, 200, 3).
encodecodeHist(history(yes, no, no, yes, no, no, yes, yes, yes, yes), 969, 201, 3).
encodecodeHist(history(no, yes, no, yes, no, no, yes, yes, yes, yes), 970, 202, 3).
encodecodeHist(history(yes, yes, no, yes, no, no, yes, yes, yes, yes), 971, 203, 3).
encodecodeHist(history(no, no, yes, yes, no, no, yes, yes, yes, yes), 972, 204, 3).
encodecodeHist(history(yes, no, yes, yes, no, no, yes, yes, yes, yes), 973, 205, 3).
encodecodeHist(history(no, yes, yes, yes, no, no, yes, yes, yes, yes), 974, 206, 3).
encodecodeHist(history(yes, yes, yes, yes, no, no, yes, yes, yes, yes), 975, 207, 3).
encodecodeHist(history(no, no, no, no, yes, no, yes, yes, yes, yes), 976, 208, 3).
encodecodeHist(history(yes, no, no, no, yes, no, yes, yes, yes, yes), 977, 209, 3).
encodecodeHist(history(no, yes, no, no, yes, no, yes, yes, yes, yes), 978, 210, 3).
encodecodeHist(history(yes, yes, no, no, yes, no, yes, yes, yes, yes), 979, 211, 3).
encodecodeHist(history(no, no, yes, no, yes, no, yes, yes, yes, yes), 980, 212, 3).
encodecodeHist(history(yes, no, yes, no, yes, no, yes, yes, yes, yes), 981, 213, 3).
encodecodeHist(history(no, yes, yes, no, yes, no, yes, yes, yes, yes), 982, 214, 3).
encodecodeHist(history(yes, yes, yes, no, yes, no, yes, yes, yes, yes), 983, 215, 3).
encodecodeHist(history(no, no, no, yes, yes, no, yes, yes, yes, yes), 984, 216, 3).
encodecodeHist(history(yes, no, no, yes, yes, no, yes, yes, yes, yes), 985, 217, 3).
encodecodeHist(history(no, yes, no, yes, yes, no, yes, yes, yes, yes), 986, 218, 3).
encodecodeHist(history(yes, yes, no, yes, yes, no, yes, yes, yes, yes), 987, 219, 3).
encodecodeHist(history(no, no, yes, yes, yes, no, yes, yes, yes, yes), 988, 220, 3).
encodecodeHist(history(yes, no, yes, yes, yes, no, yes, yes, yes, yes), 989, 221, 3).
encodecodeHist(history(no, yes, yes, yes, yes, no, yes, yes, yes, yes), 990, 222, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, no, yes, yes, yes, yes), 991, 223, 3).
encodecodeHist(history(no, no, no, no, no, yes, yes, yes, yes, yes), 992, 224, 3).
encodecodeHist(history(yes, no, no, no, no, yes, yes, yes, yes, yes), 993, 225, 3).
encodecodeHist(history(no, yes, no, no, no, yes, yes, yes, yes, yes), 994, 226, 3).
encodecodeHist(history(yes, yes, no, no, no, yes, yes, yes, yes, yes), 995, 227, 3).
encodecodeHist(history(no, no, yes, no, no, yes, yes, yes, yes, yes), 996, 228, 3).
encodecodeHist(history(yes, no, yes, no, no, yes, yes, yes, yes, yes), 997, 229, 3).
encodecodeHist(history(no, yes, yes, no, no, yes, yes, yes, yes, yes), 998, 230, 3).
encodecodeHist(history(yes, yes, yes, no, no, yes, yes, yes, yes, yes), 999, 231, 3).
encodecodeHist(history(no, no, no, yes, no, yes, yes, yes, yes, yes), 1000, 232, 3).
encodecodeHist(history(yes, no, no, yes, no, yes, yes, yes, yes, yes), 1001, 233, 3).
encodecodeHist(history(no, yes, no, yes, no, yes, yes, yes, yes, yes), 1002, 234, 3).
encodecodeHist(history(yes, yes, no, yes, no, yes, yes, yes, yes, yes), 1003, 235, 3).
encodecodeHist(history(no, no, yes, yes, no, yes, yes, yes, yes, yes), 1004, 236, 3).
encodecodeHist(history(yes, no, yes, yes, no, yes, yes, yes, yes, yes), 1005, 237, 3).
encodecodeHist(history(no, yes, yes, yes, no, yes, yes, yes, yes, yes), 1006, 238, 3).
encodecodeHist(history(yes, yes, yes, yes, no, yes, yes, yes, yes, yes), 1007, 239, 3).
encodecodeHist(history(no, no, no, no, yes, yes, yes, yes, yes, yes), 1008, 240, 3).
encodecodeHist(history(yes, no, no, no, yes, yes, yes, yes, yes, yes), 1009, 241, 3).
encodecodeHist(history(no, yes, no, no, yes, yes, yes, yes, yes, yes), 1010, 242, 3).
encodecodeHist(history(yes, yes, no, no, yes, yes, yes, yes, yes, yes), 1011, 243, 3).
encodecodeHist(history(no, no, yes, no, yes, yes, yes, yes, yes, yes), 1012, 244, 3).
encodecodeHist(history(yes, no, yes, no, yes, yes, yes, yes, yes, yes), 1013, 245, 3).
encodecodeHist(history(no, yes, yes, no, yes, yes, yes, yes, yes, yes), 1014, 246, 3).
encodecodeHist(history(yes, yes, yes, no, yes, yes, yes, yes, yes, yes), 1015, 247, 3).
encodecodeHist(history(no, no, no, yes, yes, yes, yes, yes, yes, yes), 1016, 248, 3).
encodecodeHist(history(yes, no, no, yes, yes, yes, yes, yes, yes, yes), 1017, 249, 3).
encodecodeHist(history(no, yes, no, yes, yes, yes, yes, yes, yes, yes), 1018, 250, 3).
encodecodeHist(history(yes, yes, no, yes, yes, yes, yes, yes, yes, yes), 1019, 251, 3).
encodecodeHist(history(no, no, yes, yes, yes, yes, yes, yes, yes, yes), 1020, 252, 3).
encodecodeHist(history(yes, no, yes, yes, yes, yes, yes, yes, yes, yes), 1021, 253, 3).
encodecodeHist(history(no, yes, yes, yes, yes, yes, yes, yes, yes, yes), 1022, 254, 3).
encodecodeHist(history(yes, yes, yes, yes, yes, yes, yes, yes, yes, yes), 1023, 255, 3).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Implementation of private predicates and functions

:- end_module givetake.strategy.encodecode.

%%% Local Variables: 
%%% mode: mercury
%%% mode: flyspell-prog
%%% ispell-local-dictionary: "british"
%%% End:
